### ISSUE TITLE
Login/Signup button not working

### ISSUE THREAD

**Issue by abrahamalen** [commclassroom/commclassroom#107]
The button for login/signup is not working. Add a form to signup/login if the form is not added or check the bug happened with the button tag

**Comment by 17bcs1837** [comment]
I would like to work on this issue. Please assign me this issue.
I see that no login/signup form exists, as a result, no value has been provided to the "href" attribute of the Login/Signup button.

Also, please tell me:
Do we need a separate page for login/signup forms (or)
Integrate the forms on the landing page?
