### ISSUE TITLE
No cursor pointer on header button

### ISSUE THREAD

**Issue by SaadAnsari17** [commclassroom/commclassroom#116]
### What would you like to share?

The header button with the text "Checkout our most recent podcast" doesn't have a cursor:pointer CSS property.
![image](https://user-images.githubusercontent.com/94478736/200342911-3eb0d9bd-7597-498c-9344-173dc5ce9c9e.png)

**Comment by bishal7679** [comment]
Hey @SaadAnsari17 your issues #122 & #116 has been already fixed with this PR raised #81
You can surely check out whether your issues are fixed or not after this PR got merged!

**Comment by bishal7679** [comment]
Due to some conflicts #81 is waiting

**Comment by SaadAnsari17** [comment]
Okay! effects on cards can be merged as you have not included it mantainers do check it out.
