### ISSUE TITLE
Change footer UI to match with the rest of the theme

### ISSUE THREAD

**Issue by kunal-kushwaha** [commclassroom/commclassroom#117]
![Screenshot 2021-09-26 at 4 28 19 PM](https://user-images.githubusercontent.com/42698533/134804905-c159f6da-0c94-4a00-a023-5dd82a7d3b33.png)

**Comment by ShivamTyagi12345** [comment]
I would like to help

**Comment by vaibhavch11** [comment]
![Screenshot (121)](https://user-images.githubusercontent.com/66193463/134809451-ec599a14-1c57-401a-b4ac-34a8e3583549.png)

**Comment by Vaibhav-Singh21** [comment]
is this issue still open
