### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by hariomchaudhary123** [commclassroom/commclassroom#127]
### Describe the bug

This Roadmap Button is not redirected to Roadmap Section. The page is struck after clicking.

### Screenshot/ Video

![Screenshot 2022-11-13 151748](https://user-images.githubusercontent.com/93416672/201515959-95cd3e50-6e6f-4052-b759-1f38ccc4b1a0.png)

**Comment by shaikahmadnawaz** [comment]
Can I start working on this issue?

**Comment by hariomchaudhary123** [comment]
Yes! you can

**Comment by shaikahmadnawaz** [comment]
I am working on this issue. So please assign this issue to me.

**Comment by hariomchaudhary123** [comment]
yes, you can do that.

**Comment by shaikahmadnawaz** [comment]
I cross checked this issue can be solved by #126

**Comment by maddy020** [comment]
I have solved this  #126  today 
Please help my branch in merging @hariomchaudhary123

**Comment by hariomchaudhary123** [comment]
Hey How can I help you

**Comment by maddy020** [comment]
I have solved the issue
I just want to please merge my PR

**Comment by hariomchaudhary123** [comment]
But I'm not a maintainer

**Comment by hariomchaudhary123** [comment]
How I can merge

**Comment by maddy020** [comment]
Okay

**Comment by maddy020** [comment]
no issue

**Comment by hariomchaudhary123** [comment]
Hey, @AnuragThePathak please assign this issue to someone.

**Comment by AnuragThePathak** [comment]
@maddy020 first the PR https://github.com/commclassroom/commclassroom/pull/111 will be merged, thereafter we'll see the rest.

**Comment by AnuragThePathak** [comment]
@hariomchaudhary123 your issue is a duplicate one of https://github.com/commclassroom/commclassroom/issues/109 actually
