### ISSUE TITLE
Overlapping in "NUMBERS SAY IT ALL" section on mobile version

### ISSUE THREAD

**Issue by anubha-v-ardhan** [commclassroom/commclassroom#128]
As shown in screenshot below, the terms `40000+`, `2000+` and `75000+`, `500+` overlap each other

OS: Android 11
Screen size: 6.5 inch 20:9
Browser: Google Chrome for Android

<img src="https://user-images.githubusercontent.com/71918957/134828048-f6748a46-ad6c-4fed-936b-f27dd29034e3.jpg" width="250">

**Comment by AKSHATNEMA** [comment]
Yeah, I am working on this issue. I will make PR as soon as possible.

**Comment by AKSHATNEMA** [comment]
Hey Contributors and admin of this repository, kindly check the below Screenshot whether it is correct or not.I have corrected the mobile view of the count's section in this way.

![image](https://user-images.githubusercontent.com/76521428/134851685-2c60e96d-d0c0-417f-891f-a0fa482fd9cb.png)

**Comment by harkiratsm** [comment]
Great !!

**Comment by kaiwalyakoparkar** [comment]
@AKSHATNEMA Have you created PR for this? I don't see a relative PR. Could you please link the pr here?

**Comment by anubha-v-ardhan** [comment]
in favour of #134
