### ISSUE TITLE
Add issues template

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [commclassroom/commclassroom#129]
As of now, there is just a normal issue opening method. We would like to have issue templates namely `Bug`, `Feature`, `Other` in the most recent `.yml` format

**Comment by Harshal0902** [comment]
@kaiwalyakoparkar can I work on this issue?

**Comment by Soham041201** [comment]
Can i work on this?

**Comment by vaibhavch11** [comment]
@kaiwalyakoparkar so you want us to create issues related to Bug,Feature..etc,Is that what its means if i am not wrong?

**Comment by TMahato** [comment]
###ISSUE TEMPLATES
With issue forms, you can create issue templates that have customizable web form fields. You can encourage contributors to include specific, structured information by using issue forms in your repository.

Here's a sample version of the issue form
![126118262-d648daeb-49d3-4034-a7f4-17e74890b1ee](https://user-images.githubusercontent.com/80240317/134867888-557a1739-923b-4302-81c9-1eaab484a170.png)

**Comment by DevanshK08** [comment]
@kaiwalyakoparkar bug report template is already created in #132, should i make the feature and other templates?

**Comment by kaiwalyakoparkar** [comment]
@Harshal0902 Go ahead with it :) Let me know if you need any help
