### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [commclassroom/commclassroom#130]
Currently, the repo doesn't have any template for PR. This issue is for PR template in `.md` format

**Comment by harkiratsm** [comment]
Already Done @kaiwalyakoparkar

**Comment by siddhi-244** [comment]
Can I try it ?

**Comment by HarshS1611** [comment]
@kaiwalyakoparkar  may i work on this issue?

**Comment by TMahato** [comment]
> ### What happened?
> Looking to add the new PR Template released by Github into this repo.
> 
> ### What browsers are you seeing the problem on?
> _No response_
> 
> ### Relevant log output
> _No response_

**Comment by aerosol-can** [comment]
can i be assigned this issue?

**Comment by Sin-Sumit** [comment]
@kaiwalyakoparkar Please assign me to do it.

**Comment by shreyanshmalvya** [comment]
@kaiwalyakoparkar The development branch already has a Pull Request Template, Do we need to add PR template for the  master branch? Or update the one in development branch?

**Comment by siddhi-244** [comment]
> > Can I try it ?
> 
> @siddhi-244 Go ahead

Thank you.

**Comment by kaiwalyakoparkar** [comment]
> @kaiwalyakoparkar The development branch already has a Pull Request Template, Do we need to add PR template for the master branch? Or update the one in development branch?

We can have it no worries. As it's opening contribution opportunities. When me migrate we shall give dev branch the priority

**Comment by siddhi-244** [comment]
I have made a pr @kaiwalyakoparkar
