### ISSUE TITLE
bug: 'Home' and 'Team' Button highlighted when clicked on the contact us button 

### ISSUE THREAD

**Issue by Soham041201** [commclassroom/commclassroom#131]
Whenever we click on the contact us button on the home page, both home page button and team button gets highlighted, Also when clicked on the About us button, even the home button gets highlighted.

**Comment by kaiwalyakoparkar** [comment]
@Soham041201 Could you please attach images, gif's demonstrating the issue so that others can try recreating it on their end?

**Comment by Soham041201** [comment]
> @Soham041201 Could you please attach images, gif's demonstrating the issue so that others can try recreating it on their end?

Actaully i have fixed this issue . Rased a PR #133
