### ISSUE TITLE
Text alignment issue in contact-us section [i-pad view]

### ISSUE THREAD

**Issue by satyamgupta1495** [commclassroom/commclassroom#138]
![contact-us](https://user-images.githubusercontent.com/51158766/134870776-45ac61ce-3038-4afb-a540-c699801fdb52.jpeg)

**Comment by satyamgupta1495** [comment]
I wanna work on this issue!

**Comment by TMahato** [comment]
### I can solve this issue

![Screenshot (1442)](https://user-images.githubusercontent.com/80240317/134884562-99c38a8b-d25c-4d57-81c6-69152d97a4b0.png)

**Comment by JiteshKanojia** [comment]
#230  Solves this issue.
