### ISSUE TITLE
Fix individual courses page

### ISSUE THREAD

**Issue by kunal-kushwaha** [commclassroom/commclassroom#141]
![Screenshot 2021-09-27 at 5 29 46 PM](https://user-images.githubusercontent.com/42698533/134903898-dd8e4d2c-7b5c-499e-8355-2cd0acaa1c48.png)

- [ ] remove bottom space from footer
- [x] make sure footer content is same as homepage
- [ ] add 3 buttons below every video
    - [ ] assignment
    - [ ] code
    - [ ] youtube
- [x] remove login/signup from every course page

**Comment by Bhavyajain21** [comment]
I would like to work on this issue.

**Comment by Ayan-thecodeking** [comment]
Can I work on this issue @kunal-kushwaha

**Comment by kunal-kushwaha** [comment]
go ahead

**Comment by Akshad16** [comment]
hey i can work on this issue.

**Comment by oneknucklehead** [comment]
hey? can someone elaborate on the "remove bottom space from footer" part.
do we just have to align icons to the center like in the homepage?

**Comment by Bhavyajain21** [comment]
When I am opening the website on my laptop, there's no such space there at the bottom.


> hey? can someone elaborate on the "remove bottom space from footer" part.
> do we just have to align icons to the center like in the homepage?

**Comment by oneknucklehead** [comment]
> t

Exactly. I have edited my comment. please check

**Comment by oneknucklehead** [comment]
> When I am opening the website on my laptop, there's no such space there at the bottom.
Exactly. I have edited my comment, please check if we have to do something similar to that

**Comment by Bhavyajain21** [comment]
> Exactly. I have edited my comment, please check if we have to do something similar to that
> 
> > When I am opening the website on my laptop, there's no such space there at the bottom.

Yes, I guess.

**Comment by Bhavyajain21** [comment]
> Exactly. I have edited my comment, please check if we have to do something similar to that
> 
> > When I am opening the website on my laptop, there's no such space there at the bottom.

Hey, I have sent you a connection request on LinkedIn. Let's Connect.

**Comment by merouanezouaid** [comment]
I'd work on it

**Comment by vish-han** [comment]
Can I work kunal plzzzzzzz

**Comment by oneknucklehead** [comment]
Hey @kunal-kushwaha, is something like this cool?
![edit](https://user-images.githubusercontent.com/75200954/134913641-44b0b9b8-dcfe-41f4-907e-7e95525662cd.JPG)

**Comment by kunal-kushwaha** [comment]
send screenshot of entire page

**Comment by oneknucklehead** [comment]
> send screenshot of entire page

![edit](https://user-images.githubusercontent.com/75200954/134914154-cd1f4d0c-4925-4d69-a24d-27f5afd130b3.JPG)

**Comment by Bhavyajain21** [comment]
![image](https://user-images.githubusercontent.com/64700692/134921096-6d226585-b1b1-46d0-b17e-51dc81e18316.png)
Here's what I have done. Do comment on it, if some changes are required.
@kunal-kushwaha

**Comment by BrSwish23** [comment]
![image](https://user-images.githubusercontent.com/48132611/134921777-45e662ba-a913-49e9-9022-0bad0a8e7e06.png)
Hey Kunal, I have added the 3 buttons and also fixed some padding issues. Is this alright?

**Comment by kunal-kushwaha** [comment]
please share screenshot of the entire page

**Comment by BrSwish23** [comment]
![image](https://user-images.githubusercontent.com/48132611/134922230-8ac339c7-04df-4fc1-841c-5cadc67c4e92.png)
![image](https://user-images.githubusercontent.com/48132611/134922255-0a058e34-7d19-4b83-be35-fe69ec3e1a45.png)
Here it is

**Comment by BrSwish23** [comment]
![image](https://user-images.githubusercontent.com/48132611/134924485-77b36dca-718c-4f23-8f55-ab2529751671.png)
![image](https://user-images.githubusercontent.com/48132611/134924560-a44d2df5-6cab-4e57-b7b5-340ac86d56dd.png)
Sorry for spamming but added styles to the buttons and given margin to separate cards from footer

**Comment by omkargurav10** [comment]
@kunal-kushwaha 
Here are the changes made in buttons.
Hope you would liked it.



![Screenshot 2021-09-27 194856](https://user-images.githubusercontent.com/89473596/134927042-650e7c87-33a3-4883-9ede-907c1b5123b0.png)

**Comment by omkargurav10** [comment]
@kunal-kushwaha 
Here are the changes made in buttons.
Hope you would liked it
![Screenshot 2021-09-27 195711](https://user-images.githubusercontent.com/89473596/134928324-ad2b9ab2-7f70-43f4-87d1-c8d0c9567849.png)
.

**Comment by SufyaanKhateeb** [comment]
Whoever is doing this just add some margin to the top of that container.

**Comment by nikhilreddydev** [comment]
I see that there are 7 tasks in this issue. so, do we need to do all the 7 tasks to be eligible to merge the PR?

**Comment by akash-kumar44** [comment]
> ![Screenshot 2021-09-27 at 5 29 46 PM](https://user-images.githubusercontent.com/42698533/134903898-dd8e4d2c-7b5c-499e-8355-2cd0acaa1c48.png)
> 
> * [ ]  remove bottom space from footer
> * [x]  make sure footer content is same as homepage
> * [ ]  add 3 buttons below every video
>   
>   * [ ]  assignment
>   * [ ]  code
>   * [ ]  youtube
> * [x]  remove login/signup from every course page

@kunal-kushwaha I would like to work on it ...

**Comment by rajkumawat01** [comment]
@kunal-kushwaha  Is the three-button issue solved?
If not, I would like to work on it.

**Comment by rajkumawat01** [comment]
If there are more UI, I would like to solve those too.

**Comment by rajkumawat01** [comment]
If there are more UI issues, I would like to solve those too.
