### ISSUE TITLE
Change UI of courses page

### ISSUE THREAD

**Issue by kunal-kushwaha** [commclassroom/commclassroom#145]
Change the UI of the following pages to match with the main page:
- https://commclassroom.org/courses.html
- https://commclassroom.org/course-single/java-dsa-bootcamp.html
- https://commclassroom.org/course-single/git-github.html

**Comment by vish-han** [comment]
Can i do it @kunal-kushwaha ? what kind of changes you would like to see??

**Comment by Deepchavan1** [comment]
I'm working on dark theme for courses.html
coursespanel changes
before:
<img width="1410" alt="Screenshot 2021-09-27 at 7 17 16 PM" src="https://user-images.githubusercontent.com/78216590/134922184-0329cd03-6f7d-49f2-8b91-c447fd472cb8.png">

after:
<img width="1410" alt="Screenshot 2021-09-27 at 7 17 30 PM" src="https://user-images.githubusercontent.com/78216590/134922217-b43a6d81-0883-4538-9400-c59b2f113023.png">

@kunal-kushwaha , I'm confused about whether to change coursepage theme also or not ?

**Comment by ZaidKhan2002** [comment]
<img width="1426" alt="Screenshot 2021-09-27 at 7 49 44 PM" src="https://user-images.githubusercontent.com/71960989/134927147-1db1fbaa-31ec-4456-87ba-97f5068c2af2.png">
<img width="1426" alt="Screenshot 2021-09-27 at 7 50 28 PM" src="https://user-images.githubusercontent.com/71960989/134927176-e18d0638-4210-41db-aa52-ebd5a737e77a.png">


@kunal-kushwaha  will these works?

**Comment by abrahamalen** [comment]
> I'm working on dark theme for courses.html
> coursespanel changes
> before:
> <img alt="Screenshot 2021-09-27 at 7 17 16 PM" width="1410" src="https://user-images.githubusercontent.com/78216590/134922184-0329cd03-6f7d-49f2-8b91-c447fd472cb8.png">
> 
> after:
> <img alt="Screenshot 2021-09-27 at 7 17 30 PM" width="1410" src="https://user-images.githubusercontent.com/78216590/134922217-b43a6d81-0883-4538-9400-c59b2f113023.png">
> 
> @kunal-kushwaha , I'm confused about whether to change coursepage theme also or not ?

@Deepchavan1  hey the corner curves of the 3-course cards are not uniform. Check on that measurements
