### ISSUE TITLE
There is no responsivenss in website footer specially

### ISSUE THREAD

**Issue by himanshu211raj** [commclassroom/commclassroom#146]
![image](https://user-images.githubusercontent.com/55490277/134918001-01a7f44d-45cb-4b90-b4da-529bb205a6a2.png)

**Comment by vish-han** [comment]
please assign me I'm working on it ...

**Comment by vish-han** [comment]
@himanshu211raj see is this ok???
![responsive 1](https://user-images.githubusercontent.com/44545745/134925491-e57dd191-0d0f-40e1-ba95-fbcfb1d401c4.PNG)
![responsive 2](https://user-images.githubusercontent.com/44545745/134925497-bc2c7d5f-0648-4d5c-957d-9da0255643ac.PNG)

**Comment by himanshu211raj** [comment]
not ok as all details are removed instead of this we have to make it responsive not to remove any details

**Comment by Ankishoop** [comment]
anybody is working on this issue

**Comment by akash-kumar44** [comment]
@himanshu211raj can I work on this issue?

**Comment by himanshu211raj** [comment]
> @himanshu211raj can I work on this issue?

of course if anyone not working on this @kaiwalyakoparkar kindly have a look on this

**Comment by RRAJ644** [comment]
I would like to work on this issue

**Comment by Ankishoop** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/88278862/136209347-60e9e353-9135-4b3e-9302-1113c1a0e749.png)

![Screenshot (23)](https://user-images.githubusercontent.com/88278862/136209670-83661bc2-07df-4fa9-8d29-e89a719a37eb.png)


![Screenshot (24)](https://user-images.githubusercontent.com/88278862/136209484-3652d389-8f72-4aca-8d6d-601d32179172.png)


Hey have a look Is this is ok or should i do anything else
