### ISSUE TITLE
Theme button is not working for specific courses

### ISSUE THREAD

**Issue by deeksha-singh030** [commclassroom/commclassroom#147]
Theme button is not working in the specific course page and after accessing the course.

**Comment by samz5320** [comment]
i think i fixed it can i send pull req?

<img width="1440" alt="Screenshot 2021-09-27 at 8 13 18 PM" src="https://user-images.githubusercontent.com/57592361/134931211-4a7f0bfd-c605-4e4e-9ffc-85985e1b64f5.png">

**Comment by deeksha-singh030** [comment]
@samz5320 it was working fine for this page. When you go inside the courses, for that it wasn't as it has not been implemented yet about which I came to know in discord.

**Comment by Kunal0007** [comment]
I think now it is working well for both the course page and inside the individual course page.

**Comment by Maverick-01** [comment]
hey, is the issue still open, or is it resolved?
