### ISSUE TITLE
Fixed Header Overlapping content

### ISSUE THREAD

**Issue by shamilkotta** [commclassroom/commclassroom#157]
Fixed Header Overlapping content on zero scroll position
Browser - Microsoft Edge
![Capture](https://user-images.githubusercontent.com/64640025/135030027-546f2eca-c5b4-4fde-bb76-ccda4ae5ed28.PNG)

**Comment by DevanshK08** [comment]
Hey @shamilkotta Can i work on this issue?

**Comment by Deepchavan1** [comment]
can i work on this? @shamilkotta

**Comment by AnuragThePathak** [comment]
> Fixed Header Overlapping content on zero scroll position Browser - Microsoft Edge ![Capture](https://user-images.githubusercontent.com/64640025/135030027-546f2eca-c5b4-4fde-bb76-ccda4ae5ed28.PNG)

It works fine in other browser?

**Comment by Chavda-Mitul** [comment]
i am working on this
