### ISSUE TITLE
Social link redirection on same page

### ISSUE THREAD

**Issue by mrunankpawar** [commclassroom/commclassroom#161]
There is an issue for Telegram, Discord and YouTube social link redirection. Others are opening in new tab but these three are opening in current tab itself

**Comment by mrunankpawar** [comment]
I would like to work on this issue.

**Comment by prabhxjottsingh** [comment]
Hey, just wanted to know, do we have to ask things like these, before pulling request ??
I am new here, so just wanted to know, like cannot you just solve this thing and issue a pull request directly ??

**Comment by SiddhantKhisty** [comment]
@prabhxjottsingh  It is better to inform the folks here so that duplicate PR's are avoided

**Comment by prabhxjottsingh** [comment]
@SiddhantKhisty Oh okay got it, thanks

**Comment by akash-kumar44** [comment]
@mrunankpawar, @kunal-kushwaha  I would like to work on it

**Comment by Krishnapro** [comment]
Hey I would like to work on this issue #166 because I beginner so I want to start with easy. can you assign me this @kunal-kushwaha , @kaiwalyakoparkar

**Comment by rsinghcodes** [comment]
Hi @kunal-kushwaha and @kaiwalyakoparkar, Please assign it to me and I will work on this issue. I will add one more thing which will be beneficial to redirect to secure official website and not vulnerable after opening in new tab.

Thanks!
