### ISSUE TITLE
[Bug]: The theme button dosen't work on the course page

### ISSUE THREAD

**Issue by Soham041201** [commclassroom/commclassroom#168]
### Describe the bug

The theme button is not functional on the courses page

### To Reproduce

1. Go to Courses.
2. Select any one course
3. Click on theme button

### Expected Behavior

The theme should be changed on clicking the theme button

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/79072777/135428410-28034146-321e-4b68-bd2d-929ec94ad94f.png)

**Comment by amandugar** [comment]
I would Like to work on this

**Comment by Deepchavan1** [comment]
@kunal-kushwaha , I have resolved this issue for both  git-github and java-dsa-bootcamp page and also added logo to both git-github and java-dsa-bootcamp page. But while pushing the code I'm getting permission denied.

**Comment by akash-kumar44** [comment]
@kunal-kushwaha I would like to work on this issue

**Comment by namangirdhar16** [comment]
@Soham041201 is this issue still open? If yes, i would like to work on this.

**Comment by Soham041201** [comment]
> @Soham041201 is this issue still open? If yes, i would like to work on this.

The issue is open

**Comment by omkarg01** [comment]
@kaiwalyakoparkar I would like to fix this issue

**Comment by kaiwalyakoparkar** [comment]
@amandugar I have assigned this to you. Let us know if you need any help

**Comment by amandugar** [comment]
Sure I will do it and will ask if any help is needed

**Comment by amandugar** [comment]
Hey Its a Silly Thing I have fixed the bug but How to run ```npm run format``` it doesn't have package.json

**Comment by amandugar** [comment]
Hey I have Created a Pull Request Please Check if its correct

**Comment by amandugar** [comment]
I am getting conflicts when my formatter formats the code can you please tell me what type of formatter you are using
