### ISSUE TITLE
[Bug]: The Cards on the home page changes radius on hover (looks unprofessional)

### ISSUE THREAD

**Issue by Soham041201** [commclassroom/commclassroom#178]
### Describe the bug

The cards look a bit unprofessional due to unnecessary change in radius and irregular margin between text

### To Reproduce

Home Page

### Expected Behavior

A bit of change in colour and a uniform margin between texts in the card section

### Screenshot/ Video

![Screenshot from 2021-10-01 16-37-16](https://user-images.githubusercontent.com/79072777/135610224-127102fb-9d81-4dab-9ea8-9d2fffac2c38.png)

**Comment by KamalSinghKhanna** [comment]
Hi @Soham041201, I saw that I can make a try on this.

**Comment by KamalSinghKhanna** [comment]
Hey @Soham041201 How can I add changes to development branch

**Comment by Soham041201** [comment]
> Hey @Soham041201 How can I add changes to development branch
> 

Actually I have solved this issue and raised the PR for the same :) I you are asking about contributing to the development branch ,you cant contribute directly. You have to update the code and raise PR. Once the PR gets accepted your code will be merged with the development branch. Join the discord community to get guidance for the same. Happy Hacking :)
