### ISSUE TITLE
[Bug]: require changes in css

### ISSUE THREAD

**Issue by KamalSinghKhanna** [commclassroom/commclassroom#180]
### Describe the bug

In the course section when I click on the learn more button of the course containing Java interview preparation it opens me the course in the same tab but  when I click on the learn more button of Git and Github course it opens me the course in new tab.

### To Reproduce

Go to the course
click the learn more button

Their are two ways to reproduce this 
1. change the style in such a way that both the courses are open on the existing tab.
2.  change the style in such a way that both the courses are open on the new tab.

### Screenshot/ Video

![Screenshot from 2021-10-01 17-30-29](https://user-images.githubusercontent.com/78915058/135616723-e389c6ab-3990-4e1b-bf13-ac00082a6a18.png)

**Comment by chaitanya-24** [comment]
Hello @KamalSinghKhanna, I can fix this.

**Comment by Neeteshking21** [comment]
Hey @kaiwalyakoparkar. I can work on this. Would you like to assign me?

**Comment by kaiwalyakoparkar** [comment]
@Neeteshking21 Go ahead. I will assign this to you

**Comment by Neeteshking21** [comment]
@kaiwalyakoparkar . It's working well from my side.

**Comment by Neeteshking21** [comment]
Both courses are opening in the existing tab.

**Comment by Neeteshking21** [comment]
#196. I changed the code to open in a new tab.
