### ISSUE TITLE
[Bug]: dark theme button is not placed properly

### ISSUE THREAD

**Issue by pruthvirajjadhav1** [commclassroom/commclassroom#182]
### Describe the bug

When the navigation bar is clicked on the mobile view the dark theme button gets misplaced.

### Screenshot/ Video

![IMG_20211001_174711](https://user-images.githubusercontent.com/73253354/135618431-f6270964-4e53-4226-8d3f-101f0b6f1f92.jpg)

### Desktop (please complete the following information)

Device- POCO X2
OS - Android
Browser - Chrome

**Comment by chaitanya-24** [comment]
I can try to fix it.

**Comment by Aman-Deshpande** [comment]
Hey @pruthvirajjadhav1 can I work on this issue

**Comment by kaiwalyakoparkar** [comment]
> I can try to fix it.

Go ahead. I will assign this to you

**Comment by Rohit-Mehta-0** [comment]
Hey, I have resolved this issue can anyone please review it.

**Comment by kaiwalyakoparkar** [comment]
> Hey, I have resolved this issue can anyone please review it.

What do you mean by 'resolved it'? Did you make a pr?

**Comment by Rohit-Mehta-0** [comment]
yup made a pr.

**Comment by Shivansh-yadav13** [comment]
@pruthvirajjadhav1 I think you can close it, this issue has been fixed

**Comment by pruthvirajjadhav1** [comment]
Okay
