### ISSUE TITLE
[Bug]: Add Github icon for commclassroom github page in footer

### ISSUE THREAD

**Issue by rwiteshbera** [commclassroom/commclassroom#187]
### Describe the bug

In the footer section, there is Instagram, Twitter, Linkedin, Discord, youtube icon but it would be good if there is a github icon.
The github icon will be connected to https://github.com/commclassroom

### To Reproduce

![Screenshot from 2021-10-01 19-17-58](https://user-images.githubusercontent.com/73098407/135630985-6c066f3b-8d9a-4759-9edb-5e86df18357b.png)

### Expected Behavior

Github icon at the rightmost side
![Screenshot from 2021-10-01 19-20-16](https://user-images.githubusercontent.com/73098407/135631442-8c3b8dc9-6e92-49bb-8c48-2c88bf8154cf.png)

**Comment by omkarg01** [comment]
@kaiwalyakoparkar I would like to work on this issue

**Comment by rwiteshbera** [comment]
@kaiwalyakoparkar Please assign me this issue

**Comment by Neeteshking21** [comment]
I'm also ready for this.

**Comment by mRahulRoy** [comment]
> 
> ### Describe the bug
> 
> In the footer section, there is Instagram, Twitter, Linkedin, Discord, youtube icon but it would be good if there is a github icon. The github icon will be connected to https://github.com/commclassroom
> ### To Reproduce
> 
> ![Screenshot from 2021-10-01 19-17-58](https://user-images.githubusercontent.com/73098407/135630985-6c066f3b-8d9a-4759-9edb-5e86df18357b.png)
> ### Expected Behavior
> 
> Github icon at the rightmost side ![Screenshot from 2021-10-01 19-20-16](https://user-images.githubusercontent.com/73098407/135631442-8c3b8dc9-6e92-49bb-8c48-2c88bf8154cf.png)
> ### Screenshot/ Video
> 
> _No response_
> ### Desktop (please complete the following information)
> 
> _No response_
> ### Additional context
> 
> _No response_

i want to do it. it will be my first contribution.
please assign me.

**Comment by kaiwalyakoparkar** [comment]
@rwiteshbera Go ahead. Let me know if you need any help

**Comment by rwiteshbera** [comment]
@kaiwalyakoparkar Is this project involved in Hacktoberfest? I am just asking so that my pull request will be counted. Otherwise no problem, I want to contribute to improve my skill.

**Comment by kaiwalyakoparkar** [comment]
@rwiteshbera It is participating indeed

**Comment by mRahulRoy** [comment]
> 
> 
> @rwiteshbera It is participating indeed
can i work on the same issue . or that has assigned to someone?

**Comment by kaiwalyakoparkar** [comment]
> can i work on the same issue . or that has assigned to someone?
It's assigned to @rwiteshbera
