### ISSUE TITLE
[Other]: Theme button of Course page neither styled and nor working.

### ISSUE THREAD

**Issue by Neeteshking21** [commclassroom/commclassroom#189]
### Is your request related to a problem? Please describe.

The course page's theme button isn't placed properly. That's **damaging the UI of the website.**

### Describe the solution you'd like

We can add some beautiful styles and functionality to it.

**Comment by Neeteshking21** [comment]
Please assign it to me. I can fix it.

**Comment by Jassi10000** [comment]
@Neeteshking21 Can you please put a screenshot or some reference to this

**Comment by Neeteshking21** [comment]
![button](https://user-images.githubusercontent.com/62437607/135637857-0dd4cfd7-9135-4f7b-bb52-92b90da914db.png)

**Comment by Neeteshking21** [comment]
@Jassi10000.

**Comment by Neeteshking21** [comment]
also Index page's theme button's alignment not perfect.

**Comment by Neeteshking21** [comment]
![index](https://user-images.githubusercontent.com/62437607/135638243-659868fa-4389-44fe-8d20-8f4a423756ad.png)

**Comment by Jassi10000** [comment]
Okayy !!
It's nice you spotted that , just put a message here tagging any maintainer , they will surely assign you
