### ISSUE TITLE
[Feature]:  Meet the Founder Section in not working properly on hover

### ISSUE THREAD

**Issue by Amishakumari544** [commclassroom/commclassroom#192]
### Is your feature request related to a problem? Please describe.

Meet the Founder Section in not working properly on hovering .
![comm1](https://user-images.githubusercontent.com/49230384/135644779-3284b6db-89f5-4be8-a84d-b81c9f5794ac.png)
 

### Describe the solution you'd like

We should add hover transition to make it more smooth 

### Describe alternatives you've considered

We can use transition property to look more better.

**Comment by Amishakumari544** [comment]
@kaiwalyakoparkar could you check once?

**Comment by kaiwalyakoparkar** [comment]
@Amishakumari544 Nice spot. Also the social icons are small and not centered so it looks a bit off. Would you like to work on this issue?

**Comment by Amishakumari544** [comment]
yes sure.

**Comment by kaiwalyakoparkar** [comment]
@Amishakumari544 Assigned to you. Let me know if you need any help
