### ISSUE TITLE
[Bug]:  Dropdown button is not working.

### ISSUE THREAD

**Issue by Neeteshking21** [commclassroom/commclassroom#193]
### Describe the bug

The hamburger icon is not working while I'm trying with "Toggle device Toolbar" and inspect it.

### To Reproduce

1. Open Course page.
2. _**Right-click**_ and **_inspect_** it
3. Click on the **_Toggle device toolbar_**.
4. Do minimize webpage till Hamburger Icon doesn't show.
4. Now try to Open the DropDown menu.
5. See the error.

### Expected Behavior

On click on the hamburger icon, The Dropdown menu should be open.

### Screenshot/ Video

![Uploading dropdown.png…]()

### Desktop (please complete the following information)

Device - HP
OS - Windows 10 Home
Browser:- Google Chrome
Version:- Version 94.0.4606.71 (Official Build) (64-bit)

**Comment by Neeteshking21** [comment]
![dropdown](https://user-images.githubusercontent.com/62437607/135645283-0069eb15-d91b-4db6-9b8b-295720287d79.png)

**Comment by Neeteshking21** [comment]
Please assign it to me.

**Comment by Neeteshking21** [comment]
@kaiwalyakoparkar  please check it from your side.

**Comment by kaiwalyakoparkar** [comment]
@Neeteshking21 Could you please attach a gif or a video demoing this bug?

**Comment by Neeteshking21** [comment]
![error (0)](https://user-images.githubusercontent.com/62437607/135646929-835890a0-a6a6-48c0-a8c1-151d901bcbc1.gif)
@kaiwalyakoparkar

**Comment by omkarg01** [comment]
@kaiwalyakoparkar Plz assign this to me. I would like work on this.

**Comment by akash-kumar44** [comment]
@Neeteshking21, @kaiwalyakoparkar Dropdown button is working fine. We have no need of any type of change in it. 
it works fine on every browser.

**Comment by Neeteshking21** [comment]
@akash-kumar44 . try 3rd step.  ``` Click on the Toggle device toolbar. ```

**Comment by akash-kumar44** [comment]
@Neeteshking21 I do the same process and even I open website on my mobile also 
See it is working fine on mobile also 

https://user-images.githubusercontent.com/86745118/135713603-26b554f0-fa2e-48fd-b1f0-5123ab95e04b.mp4

**Comment by akash-kumar44** [comment]
@Neeteshking21 when you raised that issue then website had that issue. But after that @Kunal0007 made changes and fix that problem and also changed the theme button to switch.
So, now website is free from that issue

**Comment by omkarg01** [comment]
> @Neeteshking21 when you raised that issue then website had that issue. But after that @Kunal0007 made changes and fix that problem and also changed the theme button to switch. So, now website is free from that issue

First go to course page of java and git then try clicking on dropdown button there, it is not working.

**Comment by akash-kumar44** [comment]
@omkarg01 ok

**Comment by Neeteshking21** [comment]
@kaiwalyakoparkar

**Comment by kaiwalyakoparkar** [comment]
@Neeteshking21 what happed here?
