### ISSUE TITLE
[BUG] Anchor missing on Youtube/Discord in page

### ISSUE THREAD

**Issue by ashwinexe** [commclassroom/commclassroom#20]
![image](https://user-images.githubusercontent.com/53075480/195921624-4cbaafd1-81d9-4795-936f-1d59d3c6c079.png)
The buttons below work but are not anchored hence don't turn the cursor into hand shape.
This might confuse viewers.

**Comment by Yudee19** [comment]
@ashwinexe can I work on this bug?

**Comment by ashwinexe** [comment]
@Yudee19 go ahead! ✨

**Comment by Yudee19** [comment]
hey @ashwinexe I just ran the code in my local system and its just showing a blank screen.
can u explain why this is happening?
also is there any other way to contact you if I run into other problems?

**Comment by ashwinexe** [comment]
@Yudee19 we're making some changes to the website, I'll notify you once it's back up.

**Comment by Yudee19** [comment]
ok @ashwinexe just notify me when the website's back. 😊

**Comment by Yudee19** [comment]
hey @ashwinexe is the website up??
is the bug still present??

**Comment by AnuragThePathak** [comment]
@Yudee19 it's up now. No idea about the bug, you can check it yourself ig.
