### ISSUE TITLE
[Feature]: improving the speed of the website in development branch

### ISSUE THREAD

**Issue by daredevilteja** [commclassroom/commclassroom#204]
### Is your feature request related to a problem? Please describe.

When the images are placed inside the **public** folder, they do not get optimized when the code is pushed to production. This decreases the speed of the website.

### Describe the solution you'd like

- [ ] Move the static folder present in public to src

### Describe alternatives you've considered

It is better to add the necessary images in their respective folders

### Additional context

![issue](https://user-images.githubusercontent.com/19908328/135663434-50cb16cc-e481-4075-bd2c-36376218080b.png)

**Comment by namangirdhar16** [comment]
@daredevilteja @kaiwalyakoparkar  can i work on this?

**Comment by daredevilteja** [comment]
> @daredevilteja @kaiwalyakoparkar  can i work on this?

Yes

**Comment by namangirdhar16** [comment]
@daredevilteja after doing the above changes, how can i tell react to look for static files in src folder instead of public?

**Comment by daredevilteja** [comment]
> @daredevilteja after doing the above changes, how can i tell react to look for static files in src folder instead of public?

Just move static folder from public into src. Then we can start using those files.
