### ISSUE TITLE
[Other]: Removing material ui package from project in development branch

### ISSUE THREAD

**Issue by daredevilteja** [commclassroom/commclassroom#206]
### Is your request related to a problem? Please describe.

Remove the material ui packages from project structure

### Describe the solution you'd like

Search for the package names and run `npm remove <packagename>`

**Comment by namangirdhar16** [comment]
@daredevilteja @kaiwalyakoparkar  can i work on this issue?

**Comment by daredevilteja** [comment]
> @daredevilteja @kaiwalyakoparkar  can i work on this issue?
> 

Yes

**Comment by namangirdhar16** [comment]
@daredevilteja can you review my pull request?

**Comment by namangirdhar16** [comment]
@daredevilteja You haven't assigned this issue to me yet.

**Comment by daredevilteja** [comment]
> @daredevilteja You haven't assigned this issue to me yet.
> 

I do not have assigning rights

**Comment by namangirdhar16** [comment]
@daredevilteja ok. Whom can i ask to assign then? because if i make a pull request i can't request for review becuase i am not assigned.

**Comment by daredevilteja** [comment]
> @daredevilteja ok. Whom can i ask to assign then? because if i make a pull request i can't request for review becuase i am not assigned.

@kunal-kushwaha @harkiratsm @kaiwalyakoparkar

**Comment by namangirdhar16** [comment]
@kunal-kushwaha @harkiratsm @kaiwalyakoparkar can u assign this to me?
