### ISSUE TITLE
[Bug]: Issue with Toggle Button when Theme Changes

### ISSUE THREAD

**Issue by amandugar** [commclassroom/commclassroom#208]
### Describe the bug

Change Theme Button has no fixed State 

### To Reproduce

- Change the theme
- Refresh the page
- State of button automatically changes but theme remains same

### Expected Behavior

It should check which theme is Currently in Local Storage and then then set the UI Accordingly

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/55328714/135665293-4f49bbaa-bfb2-4859-b7f3-3c4910f70659.png)

![image](https://user-images.githubusercontent.com/55328714/135664965-69119b03-b045-4c9d-81ea-3f1f60df422e.png)

### Desktop (please complete the following information)

Device [Laptop]
OS [Windows 10]
Browser [Chrome]

### Additional context

You can clearly see moon Icon is in both in dark and light mode
But it should appear Either in Dark or Light Theme

**Comment by amandugar** [comment]
I would like to work on it

**Comment by heysujal** [comment]
@amandugar  can we collaborate to fix this

**Comment by akash-kumar44** [comment]
@kaiwalyakoparkar I would like to work  on it
