### ISSUE TITLE
Need to Update readme.md to whatever latest commits are there and details about building locally.

### ISSUE THREAD

**Issue by RAMESSESII2** [commclassroom/commclassroom#21]

**Comment by anupamishra333** [comment]
@RAMESSESII2 @kunal-kushwaha I would like to work on this issue.

**Comment by RAMESSESII2** [comment]
> I would like to work on this issue.

hey, just do it, raise a PR, and ask questions,  this is a very friendly community of learners.

**Comment by anupamishra333** [comment]
Already raised a PR kindly Check and Merge if it is alright.
