### ISSUE TITLE
[Bug]: Footer is not responsive

### ISSUE THREAD

**Issue by akash-kumar44** [commclassroom/commclassroom#214]
### Describe the bug

- When open website in mobile phone,  footer doesn't look nice 
- Looks like spacing between content of Footer is too much
- text inside Footer ( Community Classroom, Quality education....) can be well represented in mobile

### Screenshot/ Video
![Screenshot (106)](https://user-images.githubusercontent.com/86745118/135702216-551776b0-770b-47bf-b332-66cde2480931.png)
<br>
![IMG-20211002-WA0003](https://user-images.githubusercontent.com/86745118/135685869-a3aa6853-c401-4319-a9d7-9fda41538481.jpg)

**Comment by akash-kumar44** [comment]
@kaiwalyakoparkar I would like to work on it.. please assign this to me

**Comment by Shofiya2003** [comment]
Can I work on this issue?

**Comment by PAARTH2608** [comment]
I would like to work on this. Please assign it to me

**Comment by RRAJ644** [comment]
I would like to work on it to make footer responsive

**Comment by Ankishoop** [comment]
**hey anybody is working on this issue if not I  want to work on it and also plz describe how footer should look like 
means any specification**

**Comment by Ankishoop** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/88278862/136185404-5cd64661-cfee-4f53-ab21-b9cdfdfe3e26.png)


is this is ok or not
