### ISSUE TITLE
[Other]: [React] remove @material-ui and add tailwind css.

### ISSUE THREAD

**Issue by Mohit-Swain** [commclassroom/commclassroom#222]
### Is your request related to a problem? Please describe.

As described in #218 by @harkiratsm we have to use tailwind CSS for the project but now the current react development uses material-ui. So, we have to change it.

### Describe the solution you'd like

- remove material-ui and it's dependencies
- remove material-ui code in codebase
- add tailwind CSS and it's dependencies by npm
- config tailwind CSS.

**Comment by Mohit-Swain** [comment]
I want to work on it.

**Comment by harkiratsm** [comment]
We have already been worked on it
