### ISSUE TITLE
[Bug]: Theme Btn alignment for 1024px and 1440px

### ISSUE THREAD

**Issue by Shivansh-yadav13** [commclassroom/commclassroom#237]
### Describe the bug

The Theme button is not aligned properly for 1024px and 1440px width

## 1024px
![1024px](https://user-images.githubusercontent.com/87603425/135743893-cd8ae1d7-a046-4694-9a02-deb6cf4a5912.PNG)
## 1440p
![1440px](https://user-images.githubusercontent.com/87603425/135743899-9336aaf3-8692-4085-bcf3-2bbdeef6de58.PNG)

### Desktop (please complete the following information)

Device: desktop
OS: windows
Browser: Chrome

**Comment by RamanChola** [comment]
Hey, i would like to fix this.

**Comment by Drish-xD** [comment]
I'm Working on this :)

**Comment by Drish-xD** [comment]
pls review my PR ( Navbar Fix #245 )
