### ISSUE TITLE
[Bug]: Dropdown not working

### ISSUE THREAD

**Issue by omkarg01** [commclassroom/commclassroom#238]
### Describe the bug

**Its working in home page but not in course (both java-dsa and github) page. And also it is not positioned properly.**

### Screenshot/ Video

![isuue](https://user-images.githubusercontent.com/67428719/135745090-d89f5fa6-b33c-43e3-b257-f32fc454035f.gif)

**Comment by omkarg01** [comment]
@kaiwalyakoparkar I would like to work on this issue.

**Comment by UjjwalSinghDetexter** [comment]
@kaiwalyakoparkar can you please assign this to me?
