### ISSUE TITLE
[Bug]: Margin of social media icons in footer section is not appropriate

### ISSUE THREAD

**Issue by Sumandeep-Kaur** [commclassroom/commclassroom#246]
### Describe the bug

Social media icons are not properly margined especially on hover state. 
Margin should be increased between them.

### Screenshot/ Video

![Screenshot (11)](https://user-images.githubusercontent.com/77191007/135755881-8653f1c4-96aa-4536-b56c-d57303ab9731.png)

**Comment by RamanChola** [comment]
Can i work on this?

**Comment by Amishakumari544** [comment]
It has already pr
