### ISSUE TITLE
[Feature]: The UI of the card in the course section should be improved.

### ISSUE THREAD

**Issue by rsinghcodes** [commclassroom/commclassroom#249]
### Is your feature request related to a problem? Please describe.

The UI of the card in the course section is not looking good. It seems to shrink when I'm hovering over the card and of course the color contrast of the card doesn't look good either.

![course-before](https://user-images.githubusercontent.com/67682451/135761312-13d2126d-a86a-4d26-bf99-4eb7e5a5feed.png)

### Describe the solution you'd like

- A border-radius should be reduced.
- Box-shadow should be improved.
- **"Learn more"** button should be designed better.
- When hovering over the card, it should scale up and the box-shadow should be slightly darker than the non-hover state.

**Comment by rsinghcodes** [comment]
Hi @kunal-kushwaha and @kaiwalyakoparkar, please assign it to me. I would like to work on this feature.

Thanks!

**Comment by Soham041201** [comment]
> Hi @kunal-kushwaha and @kaiwalyakoparkar, please assign it to me. I would like to work on this feature.
> 
> Thanks!
Hey, I have actually raised an Issue on this and have also raised a PR for the same
Issue numer #178 PR #186

**Comment by pushpjain3** [comment]
I have made a PR regarding this #278
