### ISSUE TITLE
Migrate frontend to React

### ISSUE THREAD

**Issue by kunal-kushwaha** [commclassroom/commclassroom#25]
- [ ] Migrate the frontend to React
- [ ] Feel free to make the UI cleaner
- [ ] Remove the Login button for now from UI

Action items: 
- [ ] Set up the project
- [ ] Create individual issues

**Comment by ritik-vashist** [comment]
I would like to work on it.

**Comment by shreyas1925** [comment]
I'm in

**Comment by RakeshPotnuru** [comment]
Atleast ONE person should create all the components according to the project structure, so that people can work on individual components.

**Comment by perveen-neha** [comment]
@RakeshPotnuru  I think you are right ... we should do it in a planned manner

**Comment by ashwinexe** [comment]
Typo on 3rd point it's *Remove

**Comment by tarunchoudhary1805** [comment]
i will also work on it

**Comment by harkiratsm** [comment]
Hi kunal , I have previously worked on causefolio where Abhishek was mentor and this project was under u . Hope it clear thing . I can setup the repo and basic things and also work as a maintainer for this repo . 🚀

**Comment by tusharsadhwani** [comment]
I can help

**Comment by HarshVardhan-Omar** [comment]
Will Take it

**Comment by vd-37** [comment]
I can contribute to this.

**Comment by yash9263** [comment]
I would like to contribute. Can we use Nextjs?

**Comment by dn-flixee** [comment]
I'm in

**Comment by TheNinza** [comment]
Hey Kunal. I would love to work on this.

**Comment by kunal-kushwaha** [comment]
@harkiratsm @HarshVardhan-Omar just gave you write access. You can collab with people who have showed interest in this chat and get the frontend ready.

Make sure all discussions are in the channel on Discord. I'll make a channel for this issue.

**Comment by harshalkaigaonkar** [comment]
@kunal-kushwaha I also want to maintain this repo..

**Comment by saurabh-chaudhary-git** [comment]
What would be the next step? So, that we all can move in a cohesive manner?

**Comment by divyanshu-parihar** [comment]
Someone should make a overall wrapper , so people can individually make small components

**Comment by Zishan-7** [comment]
I would love to contribute.

**Comment by Tanish2000** [comment]
I would love to contribute.

**Comment by sahajkedia** [comment]
I would like to contribute.

**Comment by AbhishekBhatt072003** [comment]
Hey Kunal if you don't mind I can help with this. I would love to do.
I think we had to work on react to create the different components for different sections of website.
If I am not wrong.

**Comment by kunal-kushwaha** [comment]
> Someone should make a overall wrapper , so people can individually make small components

@harkiratsm @HarshVardhan-Omar you working on this right?

**Comment by HarshVardhan-Omar** [comment]
> > Someone should make a overall wrapper , so people can individually make small components
> 
> @harkiratsm @HarshVardhan-Omar you working on this right?

Yaa sure

**Comment by SoulNinja-dev** [comment]
@HarshVardhan-Omar check out the discord channel for the page layout, and components needed

**Comment by harshalkaigaonkar** [comment]
@kunal-kushwaha could I as well..

**Comment by Anubhavdxt** [comment]
I also want to work on it.

**Comment by Kunal0007** [comment]
@HarshVardhan-Omar Can I would like to contribute

**Comment by rwiteshbera** [comment]
I would like to contribute in this project.

**Comment by yash0501** [comment]
I would like to contribute to this project

**Comment by SoulNinja-dev** [comment]
Please check out #29 for the structure for the website

**Comment by Suyious** [comment]
I've worked with React and I looked at the overall plan for the website. I would like to work on this.

**Comment by NimishKashyap** [comment]
I would like to work on the front end as well as the backend!

**Comment by unknownBalak** [comment]
Hey, I don't have previous knowledge of working with open source. I have good knowledge of React. Love to contribute here.

**Comment by AsswinCR** [comment]
I would like to contribute :) !!

**Comment by alceil** [comment]
Can I work on this issue? I would like to help I have experience in making seperate react components before!

**Comment by kulkarnigaurav38** [comment]
I would also like to contribute, I have intermediate knowledge of React:)

**Comment by varunpusarla** [comment]
I would like to contribute as wel.

**Comment by daredevilteja** [comment]
> Someone should make a overall wrapper , so people can individually make small components

I have already created the overall wrapper and created components for people to contribute. the pull request is #79 and the branch is react-rewrite. @harkiratsm @HarshVardhan-Omar Please review my code and accept the pull request

**Comment by dhananjayandayalan** [comment]
I would love to contribute. I've moderate knowledge of React.

**Comment by RagibAjmal** [comment]
I am interested in contributing

**Comment by NasratTalash** [comment]
I would also be very happy to contribute to this, how we can start contributing where is the repo?

**Comment by Shivansh-yadav13** [comment]
I would also like to contribute.

**Comment by symaticvisuals** [comment]
Hey is this issue still open? I would like to work on this.

**Comment by DhruvParthasarathy** [comment]
I would love to contribute to this issue as well. @harkiratsm
