### ISSUE TITLE
[Bug]: Contact Us link is collapsed with the dark mode toggle button

### ISSUE THREAD

**Issue by yogeshrjk** [commclassroom/commclassroom#250]
### Describe the bug

Contact Us link is collapsed with the dark mode toggle button

### Screenshot/ Video

<img width="1440" alt="Screenshot 2021-10-04 at 1 10 54 PM" src="https://user-images.githubusercontent.com/65396589/135812692-387b4983-d2f6-430f-9a35-0653e1329a31.png">
<img width="1440" alt="Screenshot 2021-10-04 at 1 10 16 PM" src="https://user-images.githubusercontent.com/65396589/135812814-6bb9b6e8-2363-4381-9bea-c9862519034e.png">
<img width="1440" alt="Screenshot 2021-10-04 at 1 29 53 PM" src="https://user-images.githubusercontent.com/65396589/135815032-f809ab5a-99fd-4086-bf5a-5a2039912ab1.png">

**Comment by yogeshrjk** [comment]
Contact Us link is collapsed with the dark mode toggle button

**Comment by Drish-xD** [comment]
Already fixed in (Navbar Fix) #245 :)
