### ISSUE TITLE
Splitting  to micro-services

### ISSUE THREAD

**Issue by divyanshu-parihar** [commclassroom/commclassroom#28]
As this website is going to be a open source from very start , And a major focus of making this website  is to make people more aware  about open source  .A better idea would be  to split this project into small micro-services . So someones changes doesn't  affect anyone else changes much and bug fixing can be easily  done . And as we can see many people are willing to contribute , changes  can be quick and so to minimize  this hustle  bustle and increase  speed  this can be highly  beneficial.

**Comment by saif-malik-01** [comment]
Front-end work is not started yet. It is good if UI gets ready, then we think to implement the backend.
