### ISSUE TITLE
[Bug]: SEO of the website is bad.

### ISSUE THREAD

**Issue by irfan378** [commclassroom/commclassroom#280]
### Describe the bug

it's search engine optimization needs to be improved.
i searched community classroom on google i couldn't find this site on first page.

**Comment by sparsh-kamat** [comment]
I think this bug is now solved and can be marked closed.
I googled it in an incognito tab so my search history should affect the results.

![Screenshot 2021-11-16 at 12 53 16 PM](https://user-images.githubusercontent.com/90212861/141939389-052ca96c-2c2c-4351-b26a-b2cc1f099b17.png)
