### ISSUE TITLE
Courses Page [ React ]

### ISSUE THREAD

**Issue by harkiratsm** [commclassroom/commclassroom#285]
### Is your feature request related to a problem? Please describe.

1) Create a Courses Page 
2) We are using **tailwind css** , (so make sure you guys are using it in the Project)
3) Make use of components 
4) All the assets are provided in ```commclassroom/src/assets/static/react-web-designs/``` & ```commclassroom/src/assets/static/course-banners/```
5) Have Fun 😄 making this .
6) Design for this is in ```commclassroom/design/light-theme/courses_light/courses.png```
7) It is like a selection page where the student can select which course they wanna do , banner changes on the basis of the selection ,
8) If you need any help just tell me or @shreyanshmalvya . 

### Describe the solution you'd like

![courses (1)](https://user-images.githubusercontent.com/71957674/137263492-8825de98-1649-4c27-aad4-b22361359238.png)

### Additional context

ENJOY HACKING 🚀 !!

**Comment by lakshaycode22** [comment]
I would like to work on this issue if its not assigned to anyone yet

**Comment by harkiratsm** [comment]
> Contributing to this on development branch or react-rewrite branch?

```developement``` branch

**Comment by harkiratsm** [comment]
@lakshaycode22 go ahead , if you require any help just tell me . 😄

**Comment by lakshaycode22** [comment]
@DhruvParthasarathy Sure I will let you know
