### ISSUE TITLE
Frontend Structure

### ISSUE THREAD

**Issue by SoulNinja-dev** [commclassroom/commclassroom#29]
- #33 

### USER - SECTION
- #30 
- User dashboard - page
	- enrolled courses
	- courses list
	- pie charts with data

- User profile - page
	- Details

- User settings - page
	- basic stuff ( username change, password, email etc )

### COURSES - SECTION
- #31  
- Courses list - page
	- filtering, favourites etc
	- Custom course list ( topic based courses eg dsa, dev )

- Particular course details - select out of grid ( udemy ) - page
	- details of content, topics taught
	- Join now (add to user's course list)
	- about creator and comments
 

### ADMIN STUFF - SECTION
- #34 
- #32 
 
- Admin profile
	- Basic details

- Admin settings

**Comment by harkiratsm** [comment]
I am willing to work For this issue and for this community .

**Comment by rwiteshbera** [comment]
I would like to work on this issue.

**Comment by kunal-kushwaha** [comment]
Great work @SoulNinja-dev

**Comment by RakeshPotnuru** [comment]
@harkiratsm 
I think Kunal already assigned the issue to you - #25

**Comment by TvishaRaji** [comment]
I would like to work on this

**Comment by amandugar** [comment]
I would Like to work on this

**Comment by arpitghura** [comment]
I want to work on this issue for the courses section
