### ISSUE TITLE
Footer Improvement [ React ]

### ISSUE THREAD

**Issue by harkiratsm** [commclassroom/commclassroom#292]
### Is your feature request related to a problem? Please describe.

1) Improve the Footer Design 
2) We are using **tailwind css** , (so make sure you guys are using it in the Project)
3) Make use of components 
4) All the assets are provided in ```commclassroom/src/assets/static/react-web-designs/``` 
5) Have Fun 😄 making this .
6) Design for this is in ```commclassroom/design/light-theme/validation-footer.png```
7)  you need any help just tell me .
8) Current Footer Look like 👇 

![image](https://user-images.githubusercontent.com/71957674/138412338-49231123-08f8-4c0d-8f34-7b39a4fe1fa5.png)

Try to replicate to :poi

![image](https://user-images.githubusercontent.com/71957674/138412441-1282eb6e-88fb-4904-a8bf-8dcb5a050339.png)

9) Makes those Links also working .

### Additional context

Happy Hacking 🚀 !

**Comment by RakeshPotnuru** [comment]
@harkiratsm unpin this issue
