### ISSUE TITLE
[Bug]: Newsletter popup

### ISSUE THREAD

**Issue by Shivansh-yadav13** [commclassroom/commclassroom#297]
### Describe the bug

- The newsletter popup not disappearing after clicking on subscribe button 

### Expected Behavior

- The popup should disappear after clicking on the subscribe button

### Screenshot/ Video

![Screenshot 2021-10-24 200249](https://user-images.githubusercontent.com/87603425/138598748-d87865f6-ab5c-4a36-99c5-3c6449492a9c.png)

### Desktop (please complete the following information)

Device - PC
OS - Windows 11
Browser - Firefox

**Comment by Rajat-Dabade** [comment]
Hello @Shivansh-yadav13, If this issue still exists, I can work on this issue. You can assign this issue to me. 
Thank you.

**Comment by Shivansh-yadav13** [comment]
> ssue still exists, I can wo

The issue still exists but you can ask @uttammanani if he is not working you can work on this issue.

**Comment by Shivansh-yadav13** [comment]
> 
> 
> Hello @Shivansh-yadav13, If this issue still exists, I can work on this issue. You can assign this issue to me. Thank you.

@Rajat-Dabade , @uttammanani , anyone working on this?

**Comment by uttammanani** [comment]
> > 
> > 
> > Hello @Shivansh-yadav13, If this issue still exists, I can work on this issue. You can assign this issue to me. Thank you.
> 
> @Rajat-Dabade , @uttammanani , anyone working on this?

I am facing some issues with my laptop. Till then, if anyone want to work on it, can do it.

**Comment by Rajat-Dabade** [comment]
> > > Hello @Shivansh-yadav13, If this issue still exists, I can work on this issue. You can assign this issue to me. Thank you.
> > 
> > 
> > @Rajat-Dabade , @uttammanani , anyone working on this?
> 
> I am facing some issues with my laptop. Till then, if anyone want to work on it, can do it.

Hello @Shivansh-yadav13 , You can assign this ticket to me. I will start working on it.
Thank you.

**Comment by Shivansh-yadav13** [comment]
> 
> 
> > > > Hello @Shivansh-yadav13, If this issue still exists, I can work on this issue. You can assign this issue to me. Thank you.
> > > 
> > > 
> > > @Rajat-Dabade , @uttammanani , anyone working on this?
> > 
> > 
> > I am facing some issues with my laptop. Till then, if anyone want to work on it, can do it.
> 
> Hello @Shivansh-yadav13 , You can assign this ticket to me. I will start working on it. Thank you.

I cannot assign, you can start working on it and make pr and mention this issue in your pr

**Comment by Rajat-Dabade** [comment]
Hello @Shivansh-yadav13 
When I push the latest code, I am seeing UI like thi
<img width="1430" alt="Screenshot 2021-11-04 at 10 02 51 AM" src="https://user-images.githubusercontent.com/26198062/140258465-33baccee-edce-45fe-8287-429e0c2d2f46.png">

Not able to find the Subscribe button.
Can you please help me with that? 
Thank you.

**Comment by Shivansh-yadav13** [comment]
> 
> 
> Hello @Shivansh-yadav13 When I push the latest code, I am seeing UI like this <img alt="Screenshot 2021-11-04 at 10 02 51 AM" width="1430" src="https://user-images.githubusercontent.com/26198062/140258465-33baccee-edce-45fe-8287-429e0c2d2f46.png">
> 
> Not able to find the Subscribe button. Can you please help me with that? Thank you.

it's in the development branch.
you can use:-
`git clone --single-branch --branch development https://github.com/commclassroom/commclassroom.git`
to clone the dev branch and then push to the dev branch

**Comment by Rajat-Dabade** [comment]
Hello @Shivansh-yadav13 
I am facing this error which starting the project
<img width="1093" alt="Screenshot 2021-11-04 at 11 47 59 AM" src="https://user-images.githubusercontent.com/26198062/140266999-895d2743-07e7-4c55-b63f-839848746d83.png">

Can't resolve './Landingpage/Hero', I have checked it, This module is not present when I cloned the code. 
Can you please confirm?
Thank you

**Comment by Shivansh-yadav13** [comment]
@Rajat-Dabade , I am also facing the same issue, do fix it if possible.

**Comment by Rajat-Dabade** [comment]
Hello @Shivansh-yadav13, I can fix this for the sack of running the project locally, but that will be no fix for this solution.

**Comment by RakeshPotnuru** [comment]
@Shivansh-yadav13, @Rajat-Dabade, @uttammanani 
That website's (which you mentioned in the issue) source is closed source, you can't contribute to that website. 

_But if you want, you can contribute to the upcoming website which is in the **development** branch._

**Comment by Shivansh-yadav13** [comment]
> 
> 
> @Shivansh-yadav13, @Rajat-Dabade, @uttammanani That website's (which you mentioned in the issue) source is closed source, you can't contribute to that website.
> 
> _But if you want, you can contribute to the upcoming website which is in the **development** branch._

Ohk, then I will close this issue.
