### ISSUE TITLE
[Bug]: Navigation Drawer auto hide after selection not working - In Mobile Screen

### ISSUE THREAD

**Issue by AbhinavMV** [commclassroom/commclassroom#299]
### Describe the bug

In mobile screen navigation drawer is not hiding automatically after an item is selected.
For Example - In below screenshot after clicking on courses in the navigation drawer, it should hide automatically and show the courses section but it does not.

### To Reproduce

If on Desktop
1. Go to site
2. Press F11 or right click and select inspect
3. Change dimensions to MotoG4
4. Click on hamburger icon in navbar and select any option in the navigation drawer

### Expected Behavior

After selecting an option in navigation drawer it should automatically hide. And selected page should be visible

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/35369843/138611068-d1829a8c-5ccb-4f0b-be98-040f1f7dc803.png)

### Desktop (please complete the following information)

Device - Desktop
OS - Windows
Browser - Chrome
Version - 95.0

**Comment by RakeshPotnuru** [comment]
@AbhinavMV 
That website's source is a closed source, you can't contribute to that website.

**Comment by AbhinavMV** [comment]
oohh ok 
@RakeshPotnuru  should i close this issue then ? 
New to open source let me know what needs to be done.

**Comment by RakeshPotnuru** [comment]
@AbhinavMV 
Yes, you can close this issue.
If you want to contribute, you can contribute to the upcoming website which is in the **development** branch
