### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by SoulNinja-dev** [commclassroom/commclassroom#30]
// clone khan academy homepage 

## side bar
- Progress
- Show Course list
- Certificates
- Edit profile button

## main
- Resume my Courses
- show xp (xp increases after every video ( like khan academy and codedamn ))

- contact us
- cc

**Comment by TvishaRaji** [comment]
@SoulNinja-dev Hey can I work on the side bar ?

**Comment by Mayank-Sh07** [comment]
Hey @SoulNinja-dev, I'd like to develop these components. I've used Material UI to develop many responsive sidebars. I can write vanilla CSS as well.

**Comment by SoulNinja-dev** [comment]
@praveenscience is handling frontend.
