### ISSUE TITLE
[Bug]: Kunal's Instagram icon/link is not working

### ISSUE THREAD

**Issue by ShaileshKumar007** [commclassroom/commclassroom#301]
### Describe the bug

In the founder section of the website, there is an option to connect with Kunal on Instagram but because he deleted his Instagram account therefore that icon is redirecting us to a page that does not exist.

### To Reproduce

1. Go to 'https://www.commclassroom.org/'
2. Scroll down to 'FOUNDER section'
3. Click on 'instagram icon'

### Expected Behavior

Instagram icon should not be present there.

### Screenshot/ Video

![tmp](https://user-images.githubusercontent.com/71178959/139908855-ec2d8a03-8c14-4b92-bda1-42a8b6d5b260.JPG)

### Desktop (please complete the following information)

ALL

### Additional context

NA

**Comment by Rajat-Dabade** [comment]
Hello @ShaileshKumar007, you can assign this issue to me if no one is working on this issue.
Thank you.
Regards,
Rajat D

**Comment by ShaileshKumar007** [comment]
> Hello @ShaileshKumar007, you can assign this issue to me if no one is working on this. Thank you. Regards, Rajat D

Thanks @Rajat-Dabade for showing interest in this issue but I've already made a PR for this.

**Comment by RakeshPotnuru** [comment]
@ShaileshKumar007 
That website is closed source, you can't contribute to that website and you made changes to a different website (previous website).

**Comment by iamalishaikh** [comment]
Add new Instagram link

**Comment by irfan378** [comment]
He has deleted his instagram account
