### ISSUE TITLE
[Bug]: Repetition of Speaker Section under cloudnativehack page 

### ISSUE THREAD

**Issue by SuperAayush** [commclassroom/commclassroom#309]
### Describe the bug

On the website of commclassroom.org, in the page of cloudnativehack that is hackathon related to CloudNative in the section of speakers, there is the same type of cards related to the speakers getting repeated 3 times. 

### To Reproduce

1. Go to 'commclassroom.org'.
2. Click on 'Hackathon' in the navbar or header.
3. Scroll down to 'Speakers' section.
4. See the repetition of the same speakers thrice. 

### Expected Behavior

Either change the last two rows of speakers with different profiles or individual or simply remove the last two rows.

### Screenshot/ Video

<img width="1440" alt="Screenshot 2021-11-19 at 2 23 52 PM" src="https://user-images.githubusercontent.com/78820926/142595356-d68e5d27-47f8-48a3-9f65-e2085cf8baeb.png">

### Desktop (please complete the following information)

Browser- Google Chrome

### Additional context

Ask the maintainers of the repository to know the desired change that needs to be done.
Get assigned and resolve the issue.

**Comment by SuperAayush** [comment]
Assign me to solve this issue.

**Comment by sparsh-kamat** [comment]
Tried this on chrome as well as edge cant seem to encounter this bug. 
![Screenshot 2021-11-19 at 5 44 16 PM](https://user-images.githubusercontent.com/90212861/142621177-a01d969a-2b2a-4b5d-ac57-30af3bfb9245.png)
![Screenshot 2021-11-19 at 5 48 14 PM](https://user-images.githubusercontent.com/90212861/142621668-776ba599-af3f-4a9b-9e1d-eb14da852744.png)
)

**Comment by SuperAayush** [comment]
Yeah it works fine now
