### ISSUE TITLE
Courses page

### ISSUE THREAD

**Issue by SoulNinja-dev** [commclassroom/commclassroom#31]
- Search bar
	- To search for particular course / topic

- Grid of all courses with thumbnail
	- button - learn more which takes to [[parti-course page]]
	- button - to add to favourite

- Option to filter / sort
	- Filter by Topic
	- Filter by creator ( if there's gonna be more teachers )
	- Filter by length
	- Filter by rating
	- Filter by Level ( beginner, advanced )
	
- Custom course list (only for signed in)
	- Option to create custom user list like udemy's wishlist - Panel
	- Option to add courses to group similar courses according to user - Panel
	- Archived Lists - Panel

- Favourite course list (only for signed in)
	- Option in grid to favourite course  
	
	
- contact us
- CC

**Comment by yash0501** [comment]
I would like to work on this issue.

**Comment by AbhishekBhatt072003** [comment]
I think we have to split all the sections of course page into different components using react.js . That is what Kunal was saying If I am not wrong.
and for custom code list and fav list we need the access for the database to check user if they are signed in or not.

If you don't mind can I handle this issue.

**Comment by tejaswini22199** [comment]
Hi, @SoulNinja-dev  I would like to work on this issue.
