### ISSUE TITLE
wrong webpage title

### ISSUE THREAD

**Issue by Sujansinh-thakor** [commclassroom/commclassroom#325]
---
name: Bug report
about: Create a report to help us improve.
title: Bug report
labels: bug
assignees: ''

---

**Describe the Bug**
It shows DevOps in webpage title instead of Java or DSA in java ,for Data Structures & Algorithms in Java Course 

**Steps to Reproduce**

1. 
2. 
3. 
4. 

**Expected Behavior**

**Actual Behavior**

**Screenshots**
![Screenshot (532)](https://user-images.githubusercontent.com/88817533/145665827-9e9aa37f-00d6-4426-8a8f-9a401b170994.jpg)

**Additional Details**

**Comment by Shivansh-yadav13** [comment]
@Sujansinh-thakor ,  that website is not open source right now 😅

**Comment by Sujansinh-thakor** [comment]
> @Sujansinh-thakor , that website is not open source right now 😅

Yeah,I realized that after creating this issue but forgot to delete this issue ☺
