### ISSUE TITLE
homepage

### ISSUE THREAD

**Issue by SoulNinja-dev** [commclassroom/commclassroom#33]
## NAVBAR
-	Categories (dropdown) 
	-	Will have all the topics which we have courses in
	-	![[Pasted image 20210827215535.png]]

- Search Bar 
	- Search for creators
	- Search for courses
	- Search for Topic

- Profile Button
	- Takes to [[user page]]
	- Redirects to '/' if user not authenticated / logged in

- University Leader

- About Us

- Donate

- Login / Register
	- Changes to Log out once the user is logged in
	

## BODY
- Current Home page
	- # Quality Education. Free for all.
	- Explore courses which takes to [[courses page]]
	- Reasons why commclassroom >>> 
	- About us
	- Testimonials
	- Key Supporters / Sponsors
	- University leader
	- Team
	- Contact us
	- CC

**Comment by harshalkaigaonkar** [comment]
@SoulNinja-dev how to move forward with this issue?

**Comment by Kunal0007** [comment]
Can I work on this issue?

**Comment by harshalkaigaonkar** [comment]
Can I work on this issue too?

**Comment by Ciggzy1312** [comment]
If not yet assigned to anyone I can work on this issue

**Comment by Mayank-Sh07** [comment]
I would also like to develop the Navbar and related components! (React + TypeScript)

**Comment by SoulNinja-dev** [comment]
Hey please ping @praveenscience for issues related to frontend :)

**Comment by Mayank-Sh07** [comment]
Okay! @praveenscience I'd love to contribute by building the Navbar and related components, please assign this issue to me! 😁
