### ISSUE TITLE
DSA-Bootcamp-content Video frame is shrunk

### ISSUE THREAD

**Issue by sridhar-5** [commclassroom/commclassroom#35]
<img width="1792" alt="Screenshot 2021-09-06 at 10 39 00 PM" src="https://user-images.githubusercontent.com/65086710/132248019-0d1c568a-c47f-4b84-9c35-3183838a3ac9.png">

**Comment by sridhar-5** [comment]
I would like to work on this issue. Can I?

**Comment by samjn08** [comment]
> I would like to work on this issue. Can I?

But it's fine on the hosted website. Try to refresh!

**Comment by sridhar-5** [comment]
I Just tried. It's still the same. If it's dependent on browser then I'm on safari.

**Comment by sridhar-5** [comment]
okay. I just tried it on Chrome. Looks fine but safari this happens.
