### ISSUE TITLE
Git documentation has link to wrong resource in open source roadmap

### ISSUE THREAD

**Issue by PradeepRaoK** [commclassroom/commclassroom#364]

**Comment by haldaranup** [comment]
@shivaylamba can I work on this issue?

**Comment by shivaylamba** [comment]
Yes definitely @haldaranup

**Comment by haldaranup** [comment]
I tried hard but the error kept coming
(tried deleting node_modules as well)
Error: Cannot find module 'cross-spawn'
@shivaylamba can you please help

**Comment by shivaylamba** [comment]
Did you install the cross-spawn node mdoule
` npm i cross-spawn`

**Comment by haldaranup** [comment]
Yes I did that as well

**Comment by shivaylamba** [comment]
Do you mind the sharing the full error trace here?

**Comment by haldaranup** [comment]
> Do you mind the sharing the full error trace here?

![Screenshot 2022-08-20 214855](https://user-images.githubusercontent.com/76952588/185756565-594d74b6-0770-409e-b1c9-25f2a769e4a4.png)

**Comment by shivaylamba** [comment]
Can you do a global install for this package?
npm i -g cross-spawn

**Comment by haldaranup** [comment]
> Can you do a global install for this package? npm i -g cross-spawn

Still same error

**Comment by shivaylamba** [comment]
you can try to uninstall Node.js and do a clean installation again and check if that fixes. 
OR 
remove the current node modules folder and do a clean npm install again 
OR 
try to use npm-link https://docs.npmjs.com/cli/v8/commands/npm-link

**Comment by haldaranup** [comment]
> you can try to uninstall Node.js and do a clean installation again and check if that fixes. OR remove the current node modules folder and do a clean npm install again OR try to use npm-link https://docs.npmjs.com/cli/v8/commands/npm-link

Thank you so much for you valuable time @shivaylamba

**Comment by haldaranup** [comment]
@shivaylamba thank you issue resolved 
The website I forked is totally different from the original one commclassroom.org, I am confused could you please help
