### ISSUE TITLE
Wrong Link added under Android Roadmap -> Introduction to Kotlin -> Kotlin in 12 minutes on the Comm Classroom website.

### ISSUE THREAD

**Issue by AmanGit010** [commclassroom/commclassroom#377]
Current Link takes us to Android studio Installation video by Rahul Pandey -> (https://www.youtube.com/watch?v=4M0hNugPJV8&ab_channel=RahulPandey)

Correct Link for Kotlin in 12 minutes video by Rahul Pandey -> (https://www.youtube.com/watch?v=iYrgWO2oibY&t=9s&ab_channel=RahulPandey)

**Comment by SaadAnsari17** [comment]
Raise the issue in the roadmaps repo (https://github.com/commclassroom/roadmaps) so that it can be resolved quickly.

**Comment by AmanGit010** [comment]
Alright, Thanks.
