### ISSUE TITLE
[BUG] Sections not aligned in the center

### ISSUE THREAD

**Issue by inclinedadarsh** [commclassroom/commclassroom#47]
![image](https://user-images.githubusercontent.com/84132532/196731485-5b11109e-9159-49f8-8e1f-1e6339daec56.png)

Most of the sections in the website, specifically the `About Us`, `Courses`, `Events`, `Mentorship`, `Podcast`, `Blogs` and `Founder` section are not center aligned.

It seems there is extra whitespace on the left side of the sections.

**Comment by SuperAayush** [comment]
Hey @inclinedadarsh , this has been fixed!!
