### ISSUE TITLE
[ENHANCEMENT] Add `arrow` SVG in buttons in all the sections

### ISSUE THREAD

**Issue by inclinedadarsh** [commclassroom/commclassroom#48]
![image](https://user-images.githubusercontent.com/84132532/196735275-ac766642-e496-4baa-9a26-41eeab37dde2.png)

Add arrow in all the arrows in the buttons inside sub-sections of the page.
Also add a hover effect to make it feel like a button.

**Comment by inclinedadarsh** [comment]
I can work on this one.
Can you please assign this to me?

**Comment by SuperAayush** [comment]
Hey @inclinedadarsh, this has been done!!
