### ISSUE TITLE
[bug] Roadmaps link broken

### ISSUE THREAD

**Issue by prasoonmhwr** [commclassroom/commclassroom#53]
### Describe the bug

Hi,

the raodmap links are broken , is the site under maintenance.

### To Reproduce

Go to url https://commclassroom.github.io/opensource-roadmap

### Screenshot/ Video

<img width="1438" alt="Screenshot 2022-10-20 at 9 29 49 AM" src="https://user-images.githubusercontent.com/52622674/196853505-5341ea45-1d13-497f-80c0-0c4a06f71b19.png">

**Comment by AnuragThePathak** [comment]
All the roadmaps have been shifted to the GitHub repository. The roadmaps can be found in the readme files of the respective folders. As the roadmaps are now open-sourced, you can contribute to them as well.

See a certain topic or resource missing in the roadmaps? Open an issue and you can work on fixing it.

➡️  https://github.com/commclassroom/roadmaps
