### ISSUE TITLE
[bug] Greetings action not working

### ISSUE THREAD

**Issue by AnuragThePathak** [commclassroom/commclassroom#54]
### Describe the bug

As it can be observed from https://github.com/commclassroom/commclassroom/pull/51, the [greetings action](https://github.com/commclassroom/commclassroom/blob/main/.github/workflows/greetings.yaml) is not working.

Probable fixes can be adding any of the types to the [pull_request event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), preferably "open".

### Additional context
<img width="899" alt="Screen Shot 2022-10-20 at 5 09 36 PM" src="https://user-images.githubusercontent.com/75429250/196938763-9bb1e7ee-9d3e-4e96-bdc6-f0b3775b47b4.png">

Looking at the error statement it seems to be a permission related issue. @kaiwalyakoparkar might be able to provide some insights on the same https://docs.github.com/en/actions/security-guides/automatic-token-authentication.

**Comment by kaiwalyakoparkar** [comment]
@AnuragThePathak can you check once as it's running on the issues. The possible reason would be that we need to approve the actions to run for the first time contributor

**Comment by AnuragThePathak** [comment]
Not very sure if that's the case as workflows are shown as running but failing due to `Resource not accessible by integration`.

**Comment by AnuragThePathak** [comment]
Today while going through this PR https://github.com/commclassroom/commclassroom/pull/60 I found that it needed maintainer approval to run workflows as it is by a first-time contributor. But, when I ran it, the same problem occurred again.
