### ISSUE TITLE
[FIX]: <Change Favicon>

### ISSUE THREAD

**Issue by SuperAayush** [commclassroom/commclassroom#6]
Change the favicon of the app from the default react app logo to the Community Classroom logo
![Screenshot 2022-10-14 at 5 03 17 AM (2)](https://user-images.githubusercontent.com/78820926/195731355-ee6b573f-d83b-40d0-8537-2b5ca5bd9c2d.jpeg)

**Comment by asdsyd** [comment]
Hey I would like to work on this. Please add hacktoberfest label. Thanks

**Comment by kaiwalyakoparkar** [comment]
@asdsyd Thank you so much for your interest but this is currently being worked on by the team. We will open this repo for external contributions as soon as first release is out. Hope you understand :)
