### ISSUE TITLE
add a  opportunity section

### ISSUE THREAD

**Issue by MukulsinghRajpurohit** [commclassroom/commclassroom#81]
i think we should also add opportunity section such he/she can directy jump to main website without wasting time.
this will we help full that all the opportunity can be seen at one place through there respective links.

**Comment by MukulsinghRajpurohit** [comment]
in this we have to update website time to time . this may also useful for those people who are stater at open source or want to contribute in communtity by regularly removing dead links adding new stuffs  by them self will give feel to do more.

**Comment by eshan1925** [comment]
What kind off opportunity do you want ot implement

**Comment by MukulsinghRajpurohit** [comment]
About open source, jobs, competition etc.

**Comment by kunal-kushwaha** [comment]
good idea, one for later
