### ISSUE TITLE
[FEATURE]: <Add a sponsors section>

### ISSUE THREAD

**Issue by yashsehgal** [commclassroom/commclassroom#9]
To add a Sponsors section as shown in the design screenshot below
<img width="1470" alt="Screenshot 2022-10-14 at 8 56 23 AM" src="https://user-images.githubusercontent.com/62352288/195755565-bbfd91ef-6b61-4a31-95fe-d7b21c54453d.png">

**Comment by yashsehgal** [comment]
One more section is done, I have implemented the Community sponsors section
<img width="1470" alt="Screenshot 2022-10-16 at 2 03 29 AM" src="https://user-images.githubusercontent.com/62352288/196006547-0b72084d-ba98-4933-9ed2-f391e5b9b223.png">

**Comment by yashsehgal** [comment]
Hey @vickywane Thanks for showing interest. Actually the implementation of this section is done, but there's a new design requirement in which this section is not included, so maybe we can close this Issue Request?

cc: @kaiwalyakoparkar @siddhant-khisty

**Comment by vickywane** [comment]
Nice. 

Please mention me on the new design issue and I’ll take a look.

**Comment by kaiwalyakoparkar** [comment]
@yashsehgal sure I will be closing this pr then
