### ISSUE TITLE
[bug] <Text is Hidden in the button>

### ISSUE THREAD

**Issue by Priyansusahoo** [commclassroom/commclassroom#93]
### Describe the bug

Text is Hidden in the button on the top of the home page.

### Expected Behavior

A clear view of the button

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/78722016/198845336-5ac3e23e-9e6f-4f18-83e7-513b1b063ed0.png)

**Comment by Priyansusahoo** [comment]
Expected a clear view of text in the button.

**Comment by SuperAayush** [comment]
Hey @Priyansusahoo for me it is working perfectly fine in every device, can I know which browser you are using?

**Comment by Priyansusahoo** [comment]
> Hey @Priyansusahoo for me it is working perfectly fine in every device, can I know which browser you are using?

Firefox Version 106.0.2(64-bit)

**Comment by SuperAayush** [comment]
I see can you try opening it in chrome?
Firefox is not allowing the font change as well I see.

**Comment by Priyansusahoo** [comment]
yes, it works well in brave and chrome...my bad

**Comment by Priyansusahoo** [comment]
yes, it works well in brave and chrome

**Comment by Priyansusahoo** [comment]
The same goes for the youtube logo on the top right, works well with chrome but not with firefox
