### ISSUE TITLE
[bug]<Youtube logo misaligned>

### ISSUE THREAD

**Issue by Priyansusahoo** [commclassroom/commclassroom#94]
### Describe the bug

On the top right corner of the homepage, the youtube logo button looks a little misaligned towards the right.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/78722016/198846363-87e0492e-a4c4-446d-a429-12fe952016a5.png)

**Comment by SuperAayush** [comment]
Duplicate issue #44
