### ISSUE TITLE
Course details : Repetition of same courses

### ISSUE THREAD

**Issue by Krishnaraj-shankar** [commclassroom/commclassroom#95]
Path : explore more courses

There is a repetition of the same web development course for multiple times

Mobile view :

![IMG_20210911_075816](https://user-images.githubusercontent.com/85430880/132933306-6db94765-a888-44d6-8476-0095e9f83980.jpg)

Desktop view : 

![IMG_20210911_080338](https://user-images.githubusercontent.com/85430880/132933350-4749379b-3b9f-4c8f-b293-e46740d17c5e.jpg)

**Comment by Krishnaraj-shankar** [comment]
@Kunal0007

**Comment by Kunal0007** [comment]
Currently, the frontend is migrating to React.

**Comment by Krishnaraj-shankar** [comment]
Then, I close this issue
