### ISSUE TITLE
[bug] YouTube button not aligned in mobile devices

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [commclassroom/commclassroom#96]
### To Reproduce

Open Side drawer on any mobile device.

### Expected Behavior

YouTube button aligned with other buttons in the center

### Screenshot/ Video

![MP1](https://user-images.githubusercontent.com/91469717/198869166-42e56b23-13d1-4e0e-bcdc-5c3ee0670f1c.png)

**Comment by Lakshay-Pruthi** [comment]
I would like to work on this issue.

**Comment by AnuragThePathak** [comment]
@Lakshay-Pruthi ig you can fix it too in https://github.com/commclassroom/commclassroom/issues/97
